### ISSUE TITLE
建议整理成Gitbook格式

### ISSUE THREAD

**Issue by wujunze** [xianyunyh/PHP-Interview#2]
建议整理成Gitbook格式 
方便阅读和分发

**Comment by xianyunyh** [comment]
@wujunze 抽时间会整理下。感谢建议

**Comment by xianyunyh** [comment]
@wujunze gitbook格式已增加。

也可以在线阅读[https://xianyunyh.gitbooks.io/php-interview/](https://xianyunyh.gitbooks.io/php-interview/)

PS:部分章节待补充。
