### ISSUE TITLE
在Linux目录下的进程和线程的链接 链 到了shell

### ISSUE THREAD

**Issue by bestcyt** [xianyunyh/PHP-Interview#5]
在Linux目录下的进程和线程的链接 链 到了shell

**Comment by bestcyt** [comment]
还有一个错别字，在LinuxIO模型.md 中的 “阻塞、非阻塞、发送在内核和用户空间之间。”  发送-》发生

**Comment by bestcyt** [comment]
![image](https://user-images.githubusercontent.com/29520724/43177914-447f9278-8ffd-11e8-9fca-529a834b65f5.png)
排版或许可以更清晰一点0.0 ， 小小的建议啦

**Comment by xianyunyh** [comment]
已经修复了！感谢您的建议！ @bestcyt
