### ISSUE TITLE
关于匿名函数和闭包函数

### ISSUE THREAD

**Issue by bestcyt** [xianyunyh/PHP-Interview#6]
![image](https://user-images.githubusercontent.com/29520724/43298502-cf334d24-9188-11e8-9bb6-1b46244f9b97.png)
大佬，感觉应该说：在PHP中 匿名函数跟闭包函数是差不多的？

**Comment by xianyunyh** [comment]
在PHP中，匿名函数的作用，大部分作用是作为一次性函数，回调，很少作为向JavaScript那样使用闭包
```php

$fn = function(){};

$fn();

array_map(function(){},$array);
```
javascript中 为了保存内部变量
```javascript

var f = function(){
   $a=1
//产生闭包
   return function(){
   return $a++
}
}

f1 = f()
f1()//1
f1()//2
```

**Comment by bestcyt** [comment]
嗯嗯，对的，js中闭包是能访问到外部变量的，而PHP需要use；我的意思是在那句话前加个（在PHP中），会不会比较严谨点？哈哈哈我就无聊随便说说:)

**Comment by xianyunyh** [comment]
没事！ @bestcyt  相互交流而已。 PHP的匿名函数 一般就是作回调。Js的匿名函数只要是为了保存一些内部变量，产生闭包。 js的作用域和PHP的也不太一样，所以两个语言相互理解一下

```php
$a = 10;//外部变量 非全局 
function f () {
echo $a; //内部的$a 未定义
}

# use 将a加到函数的作用域下
$f1 = function () use ($a) {
    echo $a;
};
$f1();
````

```javascript
var a =  10 //全局变量
function f(){
alert(a)//10
}
```

**Comment by bestcyt** [comment]
![image](https://user-images.githubusercontent.com/29520724/43306951-6ace0e7e-91af-11e8-93b3-8fa3970e02c4.png)
@xianyunyh 大佬这边子类应该是不能用parent来获取父类的保护属性，要用this，你看看是不是酱紫？

**Comment by xianyunyh** [comment]
@bestcyt  可能我写错了! 以下是用法和官方的介绍。

感谢指正 


> 范围解析操作符（也可称作 Paamayim Nekudotayim）或者更简单地说是一对冒号 `::`，可以用于访问 **静态成员**，**类常量**，还可以用于覆盖类中的属性和方法。

```php
class A
{
    const PI = 3.14;
    public static $static_var = "A的静态变量";
    public function __construct()
    {
        echo "this is A" . "\n";
    }
}

class B extends A
{

    public function __construct()
    {
        parent::__construct();
    }
    public function test()
    {
        echo parent::PI . "\n";
        echo parent::$static_var;
    }
}

(new B())->test();
```
### 参考链接


- [范围解析操作符 ](http://php.net/manual/zh/language.oop5.paamayim-nekudotayim.php)
