### ISSUE TITLE
这边有图嘛？

### ISSUE THREAD

**Issue by bestcyt** [xianyunyh/PHP-Interview#7]
![image](https://user-images.githubusercontent.com/29520724/43434514-8ca12e08-94ae-11e8-97e4-5f8c516e8b3b.png)这边有图嘛？

**Comment by bestcyt** [comment]
![image](https://user-images.githubusercontent.com/29520724/43435613-62f87eee-94b3-11e8-923e-e0520585dd6a.png)

**Comment by xianyunyh** [comment]
已修正。 @bestcyt 第二个问题的意思是 如果一本书有1000页，有500页是目录，这本书索引就非常的低。因为目录占了 书籍的一半以上。同理，索引也是一样。索引也是需要占磁盘空间。

**Comment by bestcyt** [comment]
![image](https://user-images.githubusercontent.com/29520724/43559177-91cebaa2-963f-11e8-9f85-d3b68f7d46fa.png)
这个图403

**Comment by xianyunyh** [comment]
已更新
