### ISSUE TITLE
笔误？？？

### ISSUE THREAD

**Issue by hezhizheng** [xianyunyh/PHP-Interview#9]
## [crontab](https://github.com/xianyunyh/PHP-Interview/blob/master/Linux/crontab.md)
```
3,15 * * * * myCommand #每小时第三分钟和第五分钟执行  // 3,5 * * * *   ?
```
## [LinuxIO模型](https://github.com/xianyunyh/PHP-Interview/blob/master/Linux/LinuxIO%E6%A8%A1%E5%9E%8B.md)

```
// async ?
aysnc_read("http://www.qq.com",function($data){
    echo $data;
})
    echo "end";
```

**Comment by xianyunyh** [comment]
@hezhizheng 第一个crontab 是笔误。第二个只是举个例子。再php中，你可以使用swoole的异步函数，或者使用nodejs测试异步。PHP中大部分的函数都是阻塞同步的。我只是举个例子
